### ISSUE TITLE
Alexa wont find device

### ISSUE THREAD

**Issue by anrada73** [Aircoookie/Espalexa#167] opened 2021-03-16 17:35 UTC
Hi und thank you for your project. From March 15th, 2021 Alexa will not find any devices. I've already used your examples and unsuccessfully too. Alexa finds all Tasmota devices without any problems.

Thanks for your work.

**Comment by kawapiki** [comment] 2021-03-17 16:16
Same happend here, tested with examples. Not diggin in yet, but i want to cuz my light controller based on this lib :D
At lest heres the log:
`Connected to Xtreme
IP address: 192.168.1.151
Constructing device 1
Adding device 1
Constructing device 2
Adding device 2
Adding device 3
Espalexa Begin...
MAXDEVICES 10
Done
Got UDP!
M-SEARCH * HTTP/1.1
HOST: 239.255.255.250:1900
ST: ssdp:all
MAN: "ssdp:discover"
MX: 3


Responding search req...
Got UDP!
M-SEARCH * HTTP/1.1
HOST: 239.255.255.250:1900
ST: upnp:rootdevice
MAN: "ssdp:discover"
MX: 3


Responding search req...
Got UDP!
M-SEARCH * HTTP/1.1
HOST: 239.255.255.250:1900
ST: ssdp:all
MAN: "ssdp:discover"
MX: 3


Responding search req...
Got UDP!
M-SEARCH * HTTP/1.1
HOST: 239.255.255.250:1900
ST: upnp:rootdevice
MAN: "ssdp:discover"
MX: 3


Responding search req...
Got UDP!
M-SEARCH * HTTP/1.1
HOST: 239.255.255.250:1900
ST: ssdp:all
MAN: "ssdp:discover"
MX: 3


Responding search req...
Got UDP!
M-SEARCH * HTTP/1.1
HOST: 239.255.255.250:1900
ST: upnp:rootdevice
MAN: "ssdp:discover"
MX: 3


Responding search req...
# Responding to description.xml ... #

Send setup.xml
<?xml version="1.0" ?><root xmlns="urn:schemas-upnp-org:device-1-0"><specVersion><major>1</major><minor>0</minor></specVersion><URLBase>http://192.168.1.151:80/</URLBase><device><deviceType>urn:schemas-upnp-org:device:Basic:1</deviceType><friendlyName>Espalexa (192.168.1.151:80)</friendlyName><manufacturer>Royal Philips Electronics</manufacturer><manufacturerURL>http://www.philips.com</manufacturerURL><modelDescription>Philips hue Personal Wireless Lighting</modelDescription><modelName>Philips hue bridge 2012</modelName><modelNumber>929000226503</modelNumber><modelURL>http://www.meethue.com</modelURL><serialNumber>2cf432132526</serialNumber><UDN>uuid:2f402f80-da50-11e1-9b23-2cf432132526</UDN><presentationURL>index.html</presentationURL></device></root>
Not-Found HTTP call:
URI: /api
Body: {"devicetype": "Echo"}
AlexaApiCall
ok
devType
Not-Found HTTP call:
URI: /api/2WLEDHardQrI3WHYTHoMcXHgEspsM8ZZRpSKtBQr/lights
Body: 
AlexaApiCall
ok
l0
lAll
Not-Found HTTP call:
URI: /api
Body: {"devicetype": "Echo"}
AlexaApiCall
ok
devType
Not-Found HTTP call:
URI: /api/2WLEDHardQrI3WHYTHoMcXHgEspsM8ZZRpSKtBQr/lights
Body: 
AlexaApiCall
ok
l0
lAll
Got UDP!
M-SEARCH * HTTP/1.1
HOST: 239.255.255.250:1900
MAN: "ssdp:discover"
MX: 1
ST: urn:dial-multiscreen-org:service:dial:1
USER-AGENT: Google Chrome/89.0.4389.90 Windows


Got UDP!
M-SEARCH * HTTP/1.1
HOST: 239.255.255.250:1900
MAN: "ssdp:discover"
MX: 1
ST: urn:dial-multiscreen-org:service:dial:1
USER-AGENT: Google Chrome/89.0.4389.90 Windows


Got UDP!
M-SEARCH * HTTP/1.1
HOST: 239.255.255.250:1900
MAN: "ssdp:discover"
MX: 1
ST: urn:dial-multiscreen-org:service:dial:1
USER-AGENT: Google Chrome/89.0.4389.90 Windows


Not-Found HTTP call:
URI: /api
Body: {"devicetype": "Echo"}
AlexaApiCall
ok
devType
Not-Found HTTP call:
URI: /api/2WLEDHardQrI3WHYTHoMcXHgEspsM8ZZRpSKtBQr/lights
Body: 
AlexaApiCall
ok
l0
lAll
Got UDP!
M-SEARCH * HTTP/1.1
HOST: 239.255.255.250:1900
MAN: "ssdp:discover"
MX: 1
ST: urn:dial-multiscreen-org:service:dial:1
USER-AGENT: Google Chrome/89.0.4389.90 Windows


Not-Found HTTP call:
URI: /api
Body: {"devicetype": "Echo"}
AlexaApiCall
ok
devType
Not-Found HTTP call:
URI: /api/2WLEDHardQrI3WHYTHoMcXHgEspsM8ZZRpSKtBQr/lights
Body: 
AlexaApiCall
ok
l0
lAll
Not-Found HTTP call:
URI: /api
Body: {"devicetype": "Echo"}
AlexaApiCall
ok
devType
Not-Found HTTP call:
URI: /api/2WLEDHardQrI3WHYTHoMcXHgEspsM8ZZRpSKtBQr/lights
Body: 
AlexaApiCall
ok
l0
lAll
Not-Found HTTP call:
URI: /api
Body: {"devicetype": "Echo"}
AlexaApiCall
ok
devType
Not-Found HTTP call:
URI: /api/2WLEDHardQrI3WHYTHoMcXHgEspsM8ZZRpSKtBQr/lights
Body: 
AlexaApiCall
ok
l0
lAll
Not-Found HTTP call:
URI: /api
Body: {"devicetype": "Echo"}
AlexaApiCall
ok
devType
Not-Found HTTP call:
URI: /api/2WLEDHardQrI3WHYTHoMcXHgEspsM8ZZRpSKtBQr/lights
Body: 
AlexaApiCall
ok
l0
lAll
Not-Found HTTP call:
URI: /api
Body: {"devicetype": "Echo"}
AlexaApiCall
ok
devType
Not-Found HTTP call:
URI: /api/2WLEDHardQrI3WHYTHoMcXHgEspsM8ZZRpSKtBQr/lights
Body: 
AlexaApiCall
ok
l0
lAll
Not-Found HTTP call:
URI: /api
Body: {"devicetype": "Echo"}
AlexaApiCall
ok
devType
Not-Found HTTP call:
URI: /api/2WLEDHardQrI3WHYTHoMcXHgEspsM8ZZRpSKtBQr/lights
Body: 
AlexaApiCall
ok
l0
lAll
Got UDP!
M-SEARCH * HTTP/1.1
HOST: 239.255.255.250:1900
MAN: "ssdp:discover"
MX: 1
ST: urn:dial-multiscreen-org:service:dial:1
USER-AGENT: Google Chrome/88.0.4324.190 Windows


Got UDP!
M-SEARCH * HTTP/1.1
HOST: 239.255.255.250:1900
MAN: "ssdp:discover"
MX: 1
ST: urn:dial-multiscreen-org:service:dial:1
USER-AGENT: Microsoft Edge/89.0.774.54 Windows


Got UDP!
M-SEARCH * HTTP/1.1
HOST: 239.255.255.250:1900
MAN: "ssdp:discover"
MX: 1
ST: urn:dial-multiscreen-org:service:dial:1
USER-AGENT: Google Chrome/88.0.4324.190 Windows


Got UDP!
M-SEARCH * HTTP/1.1
HOST: 239.255.255.250:1900
MAN: "ssdp:discover"
MX: 1
ST: urn:dial-multiscreen-org:service:dial:1
USER-AGENT: Microsoft Edge/89.0.774.54 Windows


Got UDP!
M-SEARCH * HTTP/1.1
HOST: 239.255.255.250:1900
MAN: "ssdp:discover"
MX: 1
ST: urn:dial-multiscreen-org:service:dial:1
USER-AGENT: Google Chrome/88.0.4324.190 Windows


Got UDP!
M-SEARCH * HTTP/1.1
HOST: 239.255.255.250:1900
MAN: "ssdp:discover"
MX: 1
ST: urn:dial-multiscreen-org:service:dial:1
USER-AGENT: Microsoft Edge/89.0.774.54 Windows


Got UDP!
M-SEARCH * HTTP/1.1
HOST: 239.255.255.250:1900
MAN: "ssdp:discover"
MX: 1
ST: urn:dial-multiscreen-org:service:dial:1
USER-AGENT: Google Chrome/88.0.4324.190 Windows


Got UDP!
M-SEARCH * HTTP/1.1
HOST: 239.255.255.250:1900
MAN: "ssdp:discover"
MX: 1
ST: urn:dial-multiscreen-org:service:dial:1
USER-AGENT: Microsoft Edge/89.0.774.54 Windows


Got UDP!
Got UDP!
Got UDP!
Got UDP!
Got UDP!
Got UDP!
Got UDP!
Got UDP!
Got UDP!
Got UDP!
Got UDP!
Got UDP!
Got UDP!
Got UDP!
Got UDP!
Got UDP!
Got UDP!
Got UDP!
Got UDP!
Got UDP!
Got UDP!
`

**Comment by rferrari81** [comment] 2021-03-18 16:42
hi everyone, me too alexa can't find the device

**Comment by eos1d3** [comment] 2021-03-20 05:04
This kind of hacking local Alexa API always won't last. This is not the first time since the release of the library. It usually works for a while and then is killed by Alexa changes. I am seeing fauxmoESP is the same.

**Comment by anrada73** [comment] 2021-03-20 19:03
I implemented the Alexa control via IFTTT. It also works with the Google Assistant. Sinric Pro works too.

**Comment by rferrari81** [comment] 2021-03-20 19:07
ifttt only has 3 free triggers and sinric seems to me to be free until august

**Comment by anrada73** [comment] 2021-03-20 19:17
Sinric.pro

**Comment by nehulagr** [comment] 2021-03-20 21:05
Siniric pro looks like a solution in this. But ESPAlexa actually made things quite simple. Is there any alternative to this? Like fauxmos or Espalexa. 

As for the time being both the library is not working. I can confirm from last 15 days for me. I had same logs. I guess we again need some work around for the same. 

Thank you!

**Comment by eos1d3** [comment] 2021-03-20 21:12
Espressif has Rainmaker which is free for develpers. It supports Google Assistant, Alexa and Home kit.

**Comment by barneyz** [comment] 2021-03-21 11:18
sinric will be switched off and sinric.pro is 3$ per lamp/device channel and year, so a house with 30 devices is 90$ a year (profiteering as it's best!).
I'am looking for openHAB running on a Rasberry Pi 4 B and reprogramming all devices with a mqtt-solutions(cloudfree).
DiyHue on Rasberry Pi 4 B and and ESP-devices can also be a possibility (cloudfree).

But i think i will wait some time if the ESPalexa problems can be fixed.

**Comment by bebhav** [comment] 2021-03-21 14:46
I'm also facing the same problem!!! 
Also from the morning, I have tried many solutions but looks like nothing is the best fit! 
Esp Rainmaker doesn't support ESP8266
sinric is chargeable after three devices!
Only wemos is working currently, which can be used only for on-off.  

Hope this will get fixed soon.

**Comment by eos1d3** [comment] 2021-03-21 15:30
$3 per year is definitely over-priced. I know from one business platform, one can charge the device with less than USD 0.5 for cloud free. And each device is charged ONCE. Of course it involves high volume for business applications.

I do test this library a long time ago but I never use it as I find it always have problem. Once a problem is fixed, another problem will soon arrive. This just like a cat and mouse game and it never ends. Does Amazon change their design to break the code? I really do not know.

**Comment by anrada73** [comment] 2021-03-21 16:12
in my opinion, every project should cost something.  So everyone gets support and developers won't work for free.  Time also costs money, please don't forget.

**Comment by oponyx** [comment] 2021-03-21 23:23
For those who's having discovery issues please try replacing the original   espalexa.h file with this one and let know 
https://github.com/oponyx/Espalexa/blob/master/src/Espalexa.h
Works in my setup...

**Comment by Aircoookie** [comment] 2021-03-21 23:56
@oponyx you're amazing! While your fix did not work out of the box for me (need `%02X` instead of `%2X` for the mac octets, otherwise they are not prepended zeros but spaces in  case the value is <16), this indeed seems to fix discovery! I will publish a version 2.7.0 incorporating the fix tomorrow.

@eos1d3 you are completely right, Local Hue API is a complete cat and mouse game. Somehow they luckily still keep it kind of supported, but always switch stuff around for some reason every few months. Can't re-iterate enough:
**Don't even think about using this library for anything beyond hobbyist applications** 😄

**Comment by oponyx** [comment] 2021-03-22 00:06
Very well!

**Comment by anrada73** [comment] 2021-03-22 06:37
> For those who's having discovery issues please try replacing the original espalexa.h file with this one and let know
> https://github.com/oponyx/Espalexa/blob/master/src/Espalexa.h
> Works in my setup...

Thanks, its work now.

**Comment by barneyz** [comment] 2021-03-22 08:45
Discovery ist working well again on 
- Echo Dot 3
- Echo Dot 3 Clock
- Echo Plus 2

@eos1d3: "Once a problem is fixed, another problem will soon arrive. This just like a cat and mouse game and it never ends. "
Yes, but i am sure, between november and march they made an error in the Echo-software, which affects also other devices on the market outside espalexa and was corrected two weeks ago:
Before November the devices must send an unique id like "uniqueid:00:17:88:01:03:7f:54:41-0x",
from Nov '20 until Mar '21 ist must be "uniqueid:00:17:88:01:03:7f"
and from Mar '21 again  "uniqueid:00:17:88:01:03:7f:54:41-0x".
In november i had question marks about the change with the unique id -xx", it was implausible..

**Comment by Aircoookie** [comment] 2021-03-22 10:16
The fix has now been merged and v2.7.0 published :) Please test!

**Comment by quilimari** [comment] 2021-03-22 12:46
Is OK now, thanks you very much

**Closed** 2021-03-22 13:57 UTC
